name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: 

    runs-on: ubuntu-latest


    steps: 
    - uses: actions/checkout@v3

    - name: configure
      run: |
    - name: Install dependencies
      run: |

    - name: Run check
      run: |

    - name: Run distcheck
      run: |
